#!/bin/sh

set -e

case "$1" in
    remove|purge)
        # remove Tweetian SQLite database
        rm -rf /home/user/.local/share/data/Tweetian
        # remove Tweetian thumnbails
        rm -rf /home/user/.thumbnails/tweetian
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`\$1'" >&2
        exit 1
    ;;
esac

exit 0
